kind: Secret
apiVersion: v1
metadata:
  name: sealed-secrets-key
  labels:
    sealedsecrets.bitnami.com/sealed-secrets-key: active
stringData:
  tls.crt: |
    {{- .Values.sealing.crt | nindent 4 }}
  tls.key: |
    {{- .Values.sealing.key | nindent 4 }}
type: kubernetes.io/tls
